const Images = {
  images: {
    slides_1: require('../assets/images/onboarding1.png'),
    slides_2: require('../assets/images/onboarding2.png'),
    slides_3: require('../assets/images/onboarding3.png'),
    slides_4: require('../assets/images/onboarding4.png'),
  },
  logos: {},
  backgrounds: {
    intro: require('../assets/images/intro.jpg'),
  },
  icons: {},
  background: {
    DVC_background: require('../Images/DVC_background.jpg'),
    infobackground: require('../Images/infobackground.jpg'),
    bg: require('../Images/bg.jpg'),
    logo: require('../Images/TD-logo.png'),
    trongdong: require('../Images/trongdong.png'),
    DL_bg: require('../Images/DL_bg.jpg'),
    hotel: require('../Images/hotel.png'),
    product: require('../Images/design.png'),
    destination: require('../Images/destination.png'),
    promotion: require('../Images/promotion.png'),
    team: require('../Images/team.png'),
    guide: require('../Images/tour-guide.png'),
    shield: require('../Images/shield.png'),
    help: require('../Images/help.png'),
    doctor: require('../Images/doctor.png'),
    firefighter: require('../Images/firefighter.png'),
    policeman: require('../Images/policeman.png'),
    stage: require('../Images/stage.png'),
    YT_bg: require('../Images/YT_bg.jpg'),
    virus: require('../Images/virus.png'),
    idcard: require('../Images/id-card.png'),
    injection: require('../Images/injection.png'),
    medicine: require('../Images/medicine.png'),
    hospital: require('../Images/hospital.png'),
    BHYT_MT: require('../Images/BHYT_MT.jpg'),
    BHYT_MS: require('../Images/BHYT_MS.jpg'),
    cccd: require('../Images/cccd.png'),
    checked: require('../Images/checked.png'),
    key: require('../Images/key.png'),
    messaging: require('../Images/messaging.png'),
    dgn_bg: require('../Images/dgn_bg.jpg'),
    pharmacy: require('../Images/pharmacy.png'),
    bg_top: require('../Images/bg_top.jpg'),
    tet2: require('../Images/tet2.jpg'),
    responsive: require('../Images/responsive.png'),
    service: require('../Images/service.png'),
    box: require('../Images/box.png'),
    placeholder: require('../Images/placeholder.png'),
    loupe: require('../Images/loupe.png'),
    NamDinh: require('../Images/NamDinh.jpg'),
    login: require('../Images/login.png'),
    facered: require('../Images/facered.png'),
    faceyellow: require('../Images/faceyellow.png'),
    facepurple: require('../Images/facepurple.png'),
    intro_bg: require('../Images/intro_bg.jpg'),
    intro_NguoiDan: require('../Images/intro_NguoiDan.png'),
    intro_DuLich: require('../Images/intro_DuLich.jpg'),
    slldt: require('../Images/slldt.png'),
    diemdanh: require('../Images/diemdanh.png'),
    dlbackground: require('../Images/dlbackground.jpg'),
  },
};

export default Images;
